### ISSUE TITLE
If chapters have images, txt file is empty

### ISSUE THREAD

**Issue by jpleite** [Attt/epub2audiobook#1]
Hi. Saw your changes. Nice work! If chapters have images, txt file only has image captions and the res of the chapter is not saved. Id the chapter has no images everything work great

**Comment by Attt** [comment]
@jpleite  thx for watching! I just converted several epub files with some chapters contains images, and everything works fine. so... could you please tell me the epub file? and, btw, pull request is welcome.

**Comment by jpleite** [comment]
thanks @Attt . Please try with any of this epub https://www.dropbox.com/s/qzai29am0uomll9/ebooks.zip?dl=1

It would also be nice to use "say" from macOS as an option instead of edge_tts. In some languages it does a better job

**Comment by Attt** [comment]
@jpleite I think this issue has been resolved. (Tried the epub file you provided, the txt file looks fine now)

> It would also be nice to use "say" from macOS as an option instead of edge_tts. In some languages it does a better job

Thanks for the suggestion, I might consider adding this option if I have time (currently the epub ​​I read are written in English, Japanese and Chinese, the speech generated by edge_tts may sound more natural)

**Comment by Attt** [comment]
Hi @jpleite ,good to tell you now you can choose to use "say" from macOS as a new tts method just with `--tts_method mac_say` option.

**Comment by jpleite** [comment]
Hi @Attt. You're the man! Excellent work. Already tested in multiple books and chapter conversion to txt is top notch. Also, thank you for including mac_say. Appreciate your work!
